# ---------------------------------------------
# Metadata
# ---------------------------------------------
title = "flask"
author = "kondo-io"

# ---------------------------------------------
# Detection (Used to determine if this matches repo)
# ---------------------------------------------
[detectors]
file_extensions = [
  ".py"
]
